steps:

  - label: 'Unit Tests'
    commands:
      - 'ci/prepare_env_buildkite.sh'
      - 'ci/run_unit_tests.sh'

  - label: ':rocket: Upload to App Distribution'
    if: build.branch == "master" && !build.pull_request.draft
    commands:
      - 'ci/prepare_env_buildkite.sh'
      - 'ci/upload_app_distribution.sh'

